substitutions:
  device_host_name: tp-sign
  device_written_name: TP Sign

<<: !include common/nodemcu-32s.yaml

font:
  - file: "fonts/pixelmix.ttf"
    id: pixelmix_font_8
    size: 8

time:
  - platform: homeassistant
    id: esptime

spi:
  - id: hspi
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: vspi
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19

binary_sensor:
  - platform: homeassistant
    name: "TP needed in main bathroom"
    entity_id: input_boolean.tp_needed_main_bathroom
    id: tp_needed_main_bathroom
  - platform: homeassistant
    name: "TP needed in guest bathroom"
    entity_id: input_boolean.tp_needed_guest_bathroom
    id: tp_needed_guest_bathroom

display:
  - platform: max7219digit
    spi_id: hspi
    cs_pin: GPIO15
    num_chips: 4
    intensity: 7 #15
    lambda: |-
      if (id(tp_needed_main_bathroom).state || id(tp_needed_guest_bathroom).state) {
        it.turn_on_off(true);
        it.print(5, 0, id(pixelmix_font_8), "TP 4");
      } else {
        it.turn_on_off(false);
      }
  - platform: max7219digit
    spi_id: vspi
    cs_pin: GPIO5
    num_chips: 4
    intensity: 7 #15
    lambda: |-
      if (id(tp_needed_main_bathroom).state && id(tp_needed_guest_bathroom).state) {
        it.turn_on_off(true);
        it.print(5, 0, id(pixelmix_font_8), "Both");
      } else if (id(tp_needed_main_bathroom).state) {
        it.turn_on_off(true);
        it.print(6, 0, id(pixelmix_font_8), "Main");
      } else if (id(tp_needed_guest_bathroom).state) {
        it.turn_on_off(true);
        it.print(2, 0, id(pixelmix_font_8), "Guest");
      } else {
        it.turn_on_off(false);
      }

sensor:
  - platform: wifi_signal
    name: "${device_written_name} WiFi Signal"
    update_interval: 60s
